//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        public ContractDetail()
        {
            this.OrderItemDetails = new HashSet<OrderItemDetail>();
        }
    
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> OrderAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
        public virtual ICollection<OrderItemDetail> OrderItemDetails { get; set; }
    }
}
