//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemDetail
    {
        public int ID { get; set; }
        public int Order_ID { get; set; }
        public int Product_ID { get; set; }
        public decimal Rate { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ContractDetail ContractDetail { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
