//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Optimus_TradeEntities : DbContext
    {
        public Optimus_TradeEntities()
            : base("name=Optimus_TradeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClientDetail> ClientDetails { get; set; }
        public DbSet<ContractDetail> ContractDetails { get; set; }
        public DbSet<ErrorTracer> ErrorTracers { get; set; }
        public DbSet<OrderItemDetail> OrderItemDetails { get; set; }
        public DbSet<ProductDetail> ProductDetails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
